[sdl]
fullscreen = false
fullresolution = desktop
windowresolution = 1024x768
output = texture
texture_renderer = direct3d

[dosbox]
machine = svga_s3
memsize = 64

[cpu]
core = auto
cputype = auto
cpu_cycles = max
cpu_cycles_protected = max

[mixer]
nosound = false
rate = 44100

[midi]
mpu401 = intelligent
mididevice = auto

[sblaster]
sbtype = sb16
sbbase = 220
irq = 7
dma = 1
hdma = 5
sbmixer = true
oplmode = auto

[render]
aspect = true
integer_scaling = false

[speaker]
pcspeaker = impulse

[joystick]
joysticktype = auto

[serial]
serial1 = dummy
serial2 = dummy
serial3 = disabled
serial4 = disabled

[dos]
xms = true
ems = true
umb = true
keyboardlayout = auto

[autoexec]
